### ISSUE TITLE
Fabrikate allows namespaces to be added to Kubernetes objects that don't support namespaces

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/fabrikate#102]
**The Issue**
Adding namespaces to the manifest yaml files of un-namespaced objects such as ClusterRole and ClusterRoleBinding means that when those objects are applied to a cluster the `kubectl describe` function will not yield the namespace defined in the manifest yaml.

**How it affects users**
Consequently tools like kubediff that show differences between your running configuration and your version controlled configuration will report an error.

If the manifest repo in a GitOps context is supposed to match the reality of what is the cluster then we shouldn't have (or allow) namespaces on Kubernetes objects that don't allow them.

**To Reproduce:**
An example of this issue is the is in the [Istio fabrikate](https://github.com/evanlouie/fabrikate-istio) repo (part of the Cloud Native Fabrikate stack). A namespace override is applied in [common.yaml](https://github.com/evanlouie/fabrikate-istio/blob/master/config/common.yaml) file. This seems to append `namespace: istio-system` to all kubernetes objects in the Istio Helm chart at the _.metadata .namespace_ level 

For instance in the Istio helm chart template for a [ClusterRole](https://github.com/istio/istio/blob/a64b2d1f5c0c2aabbb596e738ce128ae7293e6c6/install/kubernetes/helm/istio/charts/security/templates/cleanup-secrets.yaml#L38) kind in Istio has no Namespace in the _.metadata.*_ path however a metadata.namespace is created when `namespace: istio-system` is added to _.config.namespace_ path in [common.yaml](https://github.com/evanlouie/fabrikate-istio/blob/master/config/common.yaml)

<pre>
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "2"
  labels:
    app: security
    chart: security-1.0.6
    heritage: Tiller
    release: istio
  name: istio-cleanup-secrets-<b>istio-system</b>
  <b>namespace: istio-system</b>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-cleanup-secrets-<b>istio-system</b>
subjects:
- kind: ServiceAccount
  name: istio-cleanup-secrets-service-account
  namespace: <b>istio-system</b>
</pre>

This could be an issue with the Fabrikate definition, not Fabrikate itself. It's unclear at this point.

**Expected behavior:**
When I remove `.config.Namespace` from the [common.yaml](https://github.com/evanlouie/fabrikate-istio/blob/master/config/common.yaml) `fab generate prod` produces the below with no _.metadata.namespace_ value. Note that *default* become the value for the namespace.

<pre>
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-cleanup-secrets-<b>default</b>
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
  labels:
    app: security
    chart: security-1.0.6
    heritage: Tiller
    release: istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-cleanup-secrets-<b>default</b>
subjects:
  - kind: ServiceAccount
    name: istio-cleanup-secrets-service-account
    namespace: <b>default</b>
</pre>

**Additional context:**
A list of namespaced and un-namespaced objects in Kubernetes can be seen via the commands: 
`kubectl api-resources --namespaced=true`
`kubectl api-resources --namespaced=false`

**In closing**
One to many things may be true:
- The Istio Fabrikate definition is incorrectly configured for Fabrikate
- Fabrikate has an issue
- Fabrikate should not care about Kubernetes specific schemas
- The Istio Helm chart has some sort of issue

__I'm using version 0.3.0 of Fabrikate__

**Example output from Kubediff**
Below is output from a modified version of Kubediff (that exposes more logging). Kubediff compare the local istio.yaml file (from a manifest repo) against what is on the cluster
<pre>
$ ./kubediff ../manifest-sample/cloud-native/istio/istio.yaml
File:	../manifest-sample/cloud-native/istio/istio.yaml
Checking ConfigMap.v1. 'istio-galley-configuration'
Checking ConfigMap.v1. 'istio-statsd-prom-bridge'
Checking ConfigMap.v1. 'istio-security-custom-resources'
Checking ConfigMap.v1. 'istio'
Checking ConfigMap.v1. 'istio-sidecar-injector'
Checking ServiceAccount.v1. 'istio-galley-service-account'
Checking ServiceAccount.v1. 'istio-egressgateway-service-account'
Checking ServiceAccount.v1. 'istio-ingressgateway-service-account'
Checking ServiceAccount.v1. 'istio-mixer-service-account'
Checking ServiceAccount.v1. 'istio-pilot-service-account'
Checking ServiceAccount.v1. 'istio-cleanup-secrets-service-account'
Checking <b><i>ClusterRole.v1beta1.rbac.authorization.k8s.io</i></b>  'istio-cleanup-secrets-istio-system'
diff found...
## istio-system/istio-cleanup-secrets-istio-system (ClusterRole.v1beta1.rbac.authorization.k8s.io)

<b>.metadata: 'namespace' missing</b>
Checking <b><i>ClusterRoleBinding.v1beta1.rbac.authorization.k8s.io</i></b> 'istio-cleanup-secrets-istio-system'
diff found...
## istio-system/istio-cleanup-secrets-istio-system (ClusterRoleBinding.v1beta1.rbac.authorization.k8s.io)

<b>.metadata: 'namespace' missing</b>
Checking Job.v1.batch 'istio-cleanup-secrets'
Checking ServiceAccount.v1. 'istio-security-post-install-account'
Checking ClusterRole.v1beta1.rbac.authorization.k8s.io 'istio-security-post-install-istio-system'
diff found...
...
</pre>

**Comment by timfpark** [comment]
This is an issue with Fabrikate itself and it is because we were working around a bug in helm where it doesn't apply namespaces correctly sometimes to objects that should have them when templating locally by doing the namespacing of the resources itself.  A related issue is #71.

**Comment by timfpark** [comment]
Root cause in helm: https://github.com/helm/helm/issues/3553
