### ISSUE TITLE
Migration plan for namespace object model change

### ISSUE THREAD

**Issue by timfpark** [Microsoft/fabrikate#105]
Fabrikate introduces a breaking change as part of https://github.com/Microsoft/fabrikate/commit/7f60051a545313c696f804572f924b80cade8f4d that will mean that we need to update Fabrikate components to match simultaneously with the new release of a Fabrikate build.

- [x] Merge https://github.com/timfpark/fabrikate-elasticsearch-fluentd-kibana/pull/3
- [x] Merge https://github.com/timfpark/fabrikate-prometheus-grafana/pull/2
- [x] Merge https://github.com/timfpark/fabrikate-kured/pull/2
- [x] Merge https://github.com/evanlouie/fabrikate-istio/pull/12
- [x] Merge https://github.com/bnookala/fabrikate-jaeger/pull/4
- [x] Release 0.4.0 of Fabrikate

**Comment by 4c74356b41** [comment]
ugh, is there some plan to somehow notify people using this? I mean, my builds kept working, but were generating definitions into default namespace (less than ideal).  is there some feed I can monitor, or perhaps that slack we talked about is active already?

**Comment by timfpark** [comment]
@4c74356b41 This is a good point and I'm sorry.  I will set up a Slack so we can let folks know about these sort of breaking changes in the future.
