### ISSUE TITLE
Build.sh fails to download fabrikate

### ISSUE THREAD

**Issue by 4c74356b41** [Microsoft/fabrikate#125]
**Describe the bug:**
[build.sh](https://github.com/Microsoft/bedrock/blob/master/gitops/azure-devops/build.sh) broken again, cannot download latest fabrikate release

**To Reproduce:**
queue a new fabrikate build

**Expected behavior:**
yamls generated

**Screenshots:**
fabrikate not downloaded due to broken link generated by build.sh  
https://dev.azure.com/4c74356b41/fabrikate/_build/results?buildId=107

**Additional context:**
Azure Devops build (linked above)

**Comment by 4c74356b41** [comment]
according to [this](https://api.github.com/repos/Microsoft/fabrikate/tags), someone pushed v0.5.0 tag accidentally, instead of 0.5.0. which breaks build.sh

**Comment by timfpark** [comment]
Hi @4c74356b41 - thanks for the report.  I removed the problematic tag in the Fabrikate repo and this should be resolved now.  Sorry again.

**Comment by 4c74356b41** [comment]
indeed this is working now ;) thanks
