### ISSUE TITLE
fab set command ignores "string literal" and split the word based on the period (.)

### ISSUE THREAD

**Issue by sarath-p** [Microsoft/fabrikate#136]
- fab set command ignores string literals and split the argument name to generates the config file (prod.yaml). 

- To Reproduce, run the following command:

`fab set --environment prod --subcomponent cloud-native.istio gateways.istio-ingressgateway.loadBalancerIP=40.65.120.17 gateways.istio-ingressgateway.serviceAnnotations."service.beta.kubernetes.io/azure-load-balancer-resource-group"="spin-west-rg" `

- Output from the above command:
![Screen Shot 2019-04-16 at 12 30 11 PM](https://user-images.githubusercontent.com/1954035/56239025-ccb57f00-6044-11e9-841a-45fd1218d79e.png)

- `fab generate` output based on the above config
![Screen Shot 2019-04-16 at 12 50 05 PM](https://user-images.githubusercontent.com/1954035/56239770-b6a8be00-6046-11e9-9708-ee42353d68a5.png)

- Expected behavior:
Similar to `helm template` command below, the "string literal" should not be split.

`helm template install/kubernetes/helm/istio --name istio --namespace istio-system \ --values install/kubernetes/helm/istio/values-istio-demo.yaml --output-dir . --set gateways.istio-ingressgateway.loadBalancerIP="40.65.120.17" --set gateways.istio-ingressgateway.serviceAnnotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"="spin-west-rg"`

- Output from the above command:
![Screen Shot 2019-04-16 at 12 35 25 PM](https://user-images.githubusercontent.com/1954035/56238873-603a8000-6044-11e9-803f-9a1c706c7cd9.png)

**Comment by timfpark** [comment]
The issue here is that Fabrikate is using way too simple of an algorithm to do string splitting [in this code](https://github.com/Microsoft/fabrikate/blob/0daddab922f0b0f802042c34ab5f378623bdfdaa/cmd/set.go#L21).  Instead, we should do something [like this code](https://stackoverflow.com/questions/47489745/splitting-a-string-at-space-except-inside-quotation-marks-go) to handle this correctly.
