### ISSUE TITLE
Use testdata for fixtures in place of test/fixtures

### ISSUE THREAD

**Issue by timfpark** [microsoft/fabrikate#140]
In golang, the idiomatic way to do test fixtures is to have a directory with your tests called `testdata` versus the node.js way I parroted of having a `test/fixtures` directory.  This cleanup item tracks migrating to this idiomatic method to make it easier for golang developers to contribute to the project.

See https://dave.cheney.net/2016/05/10/test-fixtures-in-go for details.

**Comment by buzzfrog** [comment]
I'll take it
