### ISSUE TITLE
Statically generated components should support remote sources

### ISSUE THREAD

**Issue by timfpark** [microsoft/fabrikate#155]
As a developer, I want to be able add Fabrikate components that remotely pull in a static resource.

For example, this [Rook Cassandra Operator](
https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/cassandra/operator.yaml
) is completely specified statically in the project website and I would like to be able to directly pull in this static file from this remote URL at install time via a component that looks something like:

```
name: fabrikate-cassandra-rook
generator: static
source: https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/cassandra/operator.yaml
```

**Comment by buzzfrog** [comment]
I can try to do this

**Comment by buzzfrog** [comment]
Sorry, I need to suspend this issue for now. :(

**Comment by shubham1172** [comment]
Hey, I am willing to work on this. Can you provide some pointers?

This is what I could think of.

* add a new method - `static`
* `source` shall contain the static URL for the resource
* `path`, `branch`, `version` will be `noop`.

**Comment by buzzfrog** [comment]
Hi
I think that your suggested solution is a good start.
Just to make sure, and what you say in the chat, it is "method" not "generator" as @timfpark suggested in the description of this issue.

**Comment by shubham1172** [comment]
Hey, isn't this already solved by https://github.com/microsoft/fabrikate/pull/254. Looks like there was a duplicate issue https://github.com/microsoft/fabrikate/issues/249.
