### ISSUE TITLE
Static component in directory that doesn't exist causes generation to fail.

### ISSUE THREAD

**Issue by timfpark** [microsoft/fabrikate#156]
When there is a statically generated component, ala:

```
- name: my-static-component
  generator: "static"
  path: "./my-static-yaml"
```

and directory `my-static-yaml` doesn't exist then during generation this causes the generation to fail in a subtle manner such that it is not immediately apparent that there was a failure.

Expected:  A normal failure message and non-zero exit code so that CI/CD system can detect that it failed.

**Comment by flostadler** [comment]
I'd love to tackle this issue. Any heads up on where to start?

**Comment by evanlouie** [comment]
hi @flostadler, thanks for taking interest in Fabrikate!

The root of the issue stems from this line: https://github.com/microsoft/fabrikate/blob/master/generators/static.go#L27

Adding some better logging/messaging when the error gets encountered would greatly improve the UX for this flow.

**Comment by flostadler** [comment]
Ok, I'm on it

**Comment by shubham1172** [comment]
@flostadler, are you still working on it? If not, I can maybe start and write a fix.

**Comment by shubham1172** [comment]
@timfpark I guess this can be closed now.

**Comment by evanlouie** [comment]
Closing. Thanks again @shubham1172 for the contribution :)
