### ISSUE TITLE
Test suite fails. case-insensitive import collision

### ISSUE THREAD

**Issue by evanlouie** [microsoft/fabrikate#157]
**Describe the bug:** Test suite fails to execute if `go get -t ./...` is run after an initial successful run of the test suite. 

One of the `Install` tests clones a helm repo with has Go code in it. The code contains a module import for `gorethink.v2` which is currently unmaintained and imports an incorrectly named module `github.com/Sirupsen/logrus`. Which should be `github.com/sirupsen/logrus` (lowercase S)

File in question: `test/fixtures/install/infra/components/efk/components/elasticsearch/stable/rethinkdb/init/rethinkdb-probe/probe.go`

**To Reproduce:** Run:

```sh
go get -v -t ./...
go test -v ./...
go get -v -t ./...
go test -v ./...
```

**Expected behavior:** Tests to execute properly

**Screenshots:**

```sh
go get -v -t ./...
Fetching https://gopkg.in/gorethink/gorethink.v2?go-get=1
Parsing meta tags from https://gopkg.in/gorethink/gorethink.v2?go-get=1 (status code 200)
get "gopkg.in/gorethink/gorethink.v2": found meta tag get.metaImport{Prefix:"gopkg.in/gorethink/gorethink.v2", VCS:"git", RepoRoot:"https://gopkg.in/gorethink/gorethink.v2"} at https://gopkg.in/gorethink/gorethink.v2?go-get=1
gopkg.in/gorethink/gorethink.v2 (download)
../../../gopkg.in/gorethink/gorethink.v2/cluster.go:10:2: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
```

**Comment by sarath-p** [comment]
Fetching project dependencies is also failing with `go get ./...` command.

**Comment by evanlouie** [comment]
@sarath-p this is caused by the same issue. Because we download helm charts (some of which have Go tests in them) into the src directory, when we do a `go get ./...` it recursively tries to get the deps for the downloaded helm charts as well (some of which are incredibly outdated and unmaintained).

https://github.com/Microsoft/fabrikate/issues/160 should properly fix this.
