### ISSUE TITLE
Add support for Before and After hooks during installation

### ISSUE THREAD

**Issue by evanlouie** [Microsoft/fabrikate#17]
As an operator, I need to be able to hook into pre/post events during component installation so I can do basic orchestration for helm charts which do not belong in a help repository.

Example:

```
{
  "name": "istio",
  "generator": "static",
  "path": "./manifests",
  "pre": "wget -q0- https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz | tar xvz",
  "post": "rm -rf istio-1.0.5",
  "subcomponents": [
    {
      "name": "istio",
      "generator": "helm",
      "path": "./istio-1.0.5/install/kubernetes/helm/istio"
    }
  ]
}

```

**Comment by evanlouie** [comment]
@timfpark heads up

**Comment by timfpark** [comment]
Looks good to me - let's have them be "pre-install" and "post-install" to later enable hooks "pre-generate" and "post-generate" if we think of a reason we need to run custom code before and after generate for some reason.

**Comment by evanlouie** [comment]
Like the idea of the `hooks` map. But I think we should probably make the value of the hooks be a list of commands so we can facilitate more complex pipelines:

```
{
  "name": "istio",
  "generator": "static",
  "path": "./manifests",
  "hooks": {
    "before-install": [
      "wget https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz",
      "tar xvz istio-1.0.5-linux.tar.gz"
    ],
    "after-install": ["rm istio-1.0.5-linux.tar.gz", "rm -rf istio-1.0.5"]
  },
  "subcomponents": [
    {
      "name": "istio",
      "generator": "helm",
      "path": "./istio-1.0.5/install/kubernetes/helm/istio"
    }
  ]
}
```

**Comment by timfpark** [comment]
Makes sense and looks cleaner - I'll do that.

**Comment by timfpark** [comment]
@evanlouie I have a PR now for the before-install and after-install hooks.

**Comment by timfpark** [comment]
Closed with https://github.com/Microsoft/fabrikate/pull/21
