### ISSUE TITLE
fab set take in a yaml file

### ISSUE THREAD

**Issue by evanlouie** [microsoft/fabrikate#190]
**As a:** operator

**I want:** `fab set...` to be able to point to a file akin to a values.yaml file for helm charts

**So that:** I can more easily pass around configurations between git repos in a flat file and parse them.

**Describe the solution you'd like:** add a `fab set -f` option which allows you to pass in a filepath

**Describe alternatives you've considered:**

**Additional context:**

**Comment by bnookala** [comment]
Fixed via https://github.com/microsoft/fabrikate/pull/201
