### ISSUE TITLE
Download filename missing version number

### ISSUE THREAD

**Issue by yradsmikham** [Microsoft/fabrikate#23]
The url to download the latest version of Fabrikate excludes the version number in the zip filename (e.g. `https://github.com/Microsoft/fabrikate/releases/download/0.1.3/fab-v-linux-amd64.zip`. Previous versions like 0.1.2 look something like this: https://github.com/Microsoft/fabrikate/releases/download/0.1.2/fab-v0.1.2-linux-amd64.zip.

**Comment by timfpark** [comment]
Fixed in https://github.com/Microsoft/fabrikate/commit/3818e84b4d21b4053716aee6391053ca0a667c3b
