### ISSUE TITLE
Add the ability to manage helm-charts versions

### ISSUE THREAD

**Issue by yarinm** [microsoft/fabrikate#238]
**As a:**
Developer
**I want:**
To manage different helm charts versions for different environments. For example I created a new version for my chart and I'd like to gradually roll it other environments. In current implementation that is impossible since either we use a predefined git url for fetching the chart or explicitly add the chart version to the chart repo path.

**Describe the solution you'd like:**
1. We should start with adding version field to helm charts-based components.
2. Maybe add a versions directory containing mapping for component to chart versions 
**Describe alternatives you've considered:**
Currently I might end up writing something of my own instead of fabrikate as I have another dependency which is related to how we internally manage application versioning

**Comment by evanlouie** [comment]
Hi @yarinm. I've added the ability to utilize the `version` field for the components with `method: helm` (in the PR mentioned above). Although this doesn't address your issue directly right now, its a first step.

I think we'll need to think more about how we could support your specific use case. Right now, config is used to configure how components should `generate`. What your use case specifies would be adding an additional environment based config layer for the `install` step.
