### ISSUE TITLE
Support remote urls for static components

### ISSUE THREAD

**Issue by timfpark** [microsoft/fabrikate#249]
As an operations person, I would like to be able to deploy the Elasticsearch operator in my cluster to be able to create Elasticsearch clusters.  The Elasticsearch operator is shipped as a static url (currently at https://download.elastic.co/downloads/eck/0.9.0/all-in-one.yaml).

Currently, using a remote static component url requires that we use prehooks to download a resource like this.  To make this easier for component writers, we should support a remote static url, and handle the download of this remote internally.

**Comment by evanlouie** [comment]
Closed in #254
