### ISSUE TITLE
All logging is written to STDERR

### ISSUE THREAD

**Issue by basvandenbrink** [microsoft/fabrikate#251]
**Describe the bug:**
Fabrikate writes all output to STDERR.

**To Reproduce:**
Execute any fabrikate command.

**Expected behavior:**
Only errors are written to STDERR, all other messages should go to STDOUT.

**Desktop:**

- OS: Linux

**Comment by evanlouie** [comment]
Hi @basvandenbrink, thanks for catching this.
This is caused from us using some of the default settings of [logrus](https://github.com/sirupsen/logrus) for logging which, by default, outputs all logs to `stderr`.

As you can see from the issue and PR below, the core maintainer has not been open to implementing or accepting any PRs to fix this.

https://github.com/sirupsen/logrus/issues/403
https://github.com/sirupsen/logrus/pull/671

I'll take some steps to resolve this on Fabrikates end this week:

- Output all logs to `stdout` by default.
- Create a wrapper logging service which will call `logrus.SetOutput(os.<Stderr|Stdout>)` as necessary.

**Comment by basvandenbrink** [comment]
@evanlouie Thanks for the quick head-up! Good to hear it is picked up.
