### ISSUE TITLE
Temporary Helm values files not cleaned from temp dir

### ISSUE THREAD

**Issue by mhenniges** [microsoft/fabrikate#265]
**Describe the bug:**

When using components of  'type: helm', fab generate leaves temporary values files behind after it completes. Over time, many thousands of these accumulate in Tempdir

**To Reproduce:**
'fab generate -v' on any 'type: helm' component; the temporary file name will be shown in the output. The file will still exist after fab generate has completed.

**Expected behavior:**
No temporary files are left after fab generate completes.

**Additional context:**

I suspect adding a simple  
```
defer os.Remove(absOverriddenPath)
```
immediately after https://github.com/microsoft/fabrikate/blob/master/generators/helm.go#L163
will fix the issue.

**Comment by edaena** [comment]
Thanks for the feedback. There's a pr incorporating your suggestion: [fabrikate/pull/282](https://github.com/microsoft/fabrikate/pull/282)
