### ISSUE TITLE
Namespace injection results in non-deterministic output

### ISSUE THREAD

**Issue by haines** [microsoft/fabrikate#272]
**Describe the bug:**

With `injectNamespace: true`, the output of `fab generate` from a Helm component is not deterministic, because the namespace injection does not preserve the order of the resources in the manifest.

This results in a spurious git diff that makes it hard to verify changes.

Without namespace injection, the output appears to be stably ordered (although https://github.com/helm/helm/issues/6843 would suggest that this is not currently guaranteed, but will be in v3.1).

**To Reproduce:**

`fab generate` from a Helm component repeatedly, diff the resulting manifests. With `injectNamespace: true`, there's always a diff; without it, there isn't.

For example, I used the following

*component.yaml*
```yaml
name: flux
type: helm
method: helm
source: https://charts.fluxcd.io
path: flux
version: 0.15.0
```

*config/common.yaml*
```yaml
namespace: flux
injectNamespace: true
```

**Expected behavior:**

Fabrikate doesn't change the ordering of the resources in the manifest that Helm outputs.

**Comment by timfpark** [comment]
Thank you @haines for the issue and PR - agreed this is a problem and thanks for the draft PR.  If you can sign the CLA, I'll merge and make a release.

**Comment by haines** [comment]
Excellent, done! I've tested the changes I made in #273 against our definitions and we're now seeing deterministic output.
