### ISSUE TITLE
Fabrikate swallowing error messages

### ISSUE THREAD

**Issue by yradsmikham** [Microsoft/fabrikate#28]
When attempting to adding new components via Fabrikate (e.g. Jaeger), any helm chart dependency failures are not displayed in logs. For example:

`ERRO[29-01-2019 15:46:19] helm template failed with:`

after investigating, the root cause of the issue was the following error:

`  jaeger git:(master) helm dependency update
Error: no repository definition for https://kubernetes-charts-incubator.storage.googleapis.com/, https://kubernetes-charts-incubator.storage.googleapis.com/. Please add them via 'helm repo add'`

**Comment by timfpark** [comment]
I have no idea why golang makes this so hard to do - but I am on it.

**Comment by timfpark** [comment]
Addressed in https://github.com/Microsoft/fabrikate/commit/99ad5419ffa0f1d4efa95093fce4d87403395a77
