### ISSUE TITLE
fab generate should validate manifests

### ISSUE THREAD

**Issue by bnookala** [Microsoft/fabrikate#29]
It's currently possible for `fab generate` to generate malformed yaml, which cannot be applied against a cluster (as a consequence of bad user input). 

After generation, we can possibly use "kubectl --validate=true --dry-run --recursive -f ./generated/generated_environment" to perform validation against the output environment.

**Comment by timfpark** [comment]
great idea - i will add that

**Comment by andrebriggs** [comment]
+1 this will be useful in the CI/CD validation as well

**Comment by timfpark** [comment]
Fixed in release 0.2.0: https://github.com/Microsoft/fabrikate/commit/35d30e63f7935f2f2d29a5dce5e70aee57116864
