### ISSUE TITLE
Support optional components or targeted components

### ISSUE THREAD

**Issue by hfgbarrigas** [microsoft/fabrikate#292]
**As a:** someone that uses Fabrikate.

**I want:** To optionally use some components when using *generate*.

**So that:** the tool is more flexible.

**Describe the solution you'd like:** support component top level field that is an array of tags (e.g: environments) that when those tags are used in generate, components eligible for creation need to have those tags present in the array.

**Describe alternatives you've considered:** None.

**Additional context:** Maybe issue #73 was meant for this ... #18 would most likely address this feature and more but might more complex to implement.

**Comment by jred55** [comment]
Duplicate of #277
