### ISSUE TITLE
Fabrikate should pull chart dependencies before generating

### ISSUE THREAD

**Issue by bnookala** [Microsoft/fabrikate#3]
Found an issue in which the jaeger chart was failing to generate due to it having other chart dependencies. Fabrikate doesn't appear to pull dependencies currently, thus failing. I had to modify the helm generation code to reveal the error (it's currently swallowed):

```
ERRO[15-01-2019 18:19:23] helm template failed with: Error: found in requirements.yaml, but missing in charts/ directory: cassandra, elasticsearch
```

**Comment by timfpark** [comment]
Are you saying that a `fab generate` failed after a `fab install` or that you think the most intuitive behavior is that it should automatically install while it generates?

The reason I don't do an install as I generate is that many folks might want to install once / generate many or directly check in dependencies (eg. a vendoring or shrinkwrap scenario) - but it might be a nice optimization that if a package(s) hasn't been installed during generate that we install it for them.

**Comment by bnookala** [comment]
@timfpark `fab generate` failed after a `fab install` because there's no handling of chart dependencies (either in fab install or fab generate). The correct behavior is to add a `helm dependency update` somewhere before generate.

**Comment by timfpark** [comment]
ah ok - i will add this at install time so the chart directory is prep'ed for generate.

**Comment by timfpark** [comment]
Fixed in https://github.com/Microsoft/fabrikate/commit/dce27f07f67ce6f7259ced83a81a3b3d23521fc6
