### ISSUE TITLE
fab instal fails with latest Helm version 3.2

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/fabrikate#300]
**Describe the bug:**
Fabrikate does not work with Helm 3.2 as described in the readme file. I had to downgrade to 2.16.1 for it to work

**To Reproduce:**

**Expected behavior:**
fab install to work

**Screenshots:**
$ fab install
INFO[01-05-2020 06:19:23] fab version 0.17.3                           
INFO[01-05-2020 06:19:23] 🔍  Using git: /usr/local/bin/git             
INFO[01-05-2020 06:19:23] 🔍  Using helm: /usr/local/bin/helm           
INFO[01-05-2020 06:19:23] 🔍  Using sh: /bin/sh                         
INFO[01-05-2020 06:19:23] 🔍  Using curl: /usr/bin/curl                 
INFO[01-05-2020 06:19:23] 👉  Initializing Helm                         
ERRO[01-05-2020 06:19:23] 🚫  exit status 1: Error: unknown command "init" for "helm"

Did you mean this?
        lint

Run 'helm --help' for usage. 
Error: exit status 1
Usage:
  fab install [flags]

**Additional context:**

**Desktop (please complete the following information):**

- OS:

$ **helm version**
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Additional context**

**Comment by evanlouie** [comment]
hi @NarmathaBala, Helm 3 support has be added to the `develop` branch and can be built yourself using by cloning and doing a `go build -o fab`. We are just waiting on a sister project to fix up some Fabrikate installation dependencies before we can cut a release with Helm 3

Take a look here for more context: https://github.com/microsoft/fabrikate/wiki/Roadmap-Updates
