### ISSUE TITLE
Build pipeline fails

### ISSUE THREAD

**Issue by edaena** [microsoft/fabrikate#308]
**Describe the bug:**
Build pipeline fails on setting up the Go workspace. 
go: cannot find GOROOT directory: /usr/local/go1.13

##[error]Bash exited with code '2'.

**To Reproduce:**
Queue a build run off of master -> [fabrikate/_build/results?buildId=5237&view=results](https://tpark.visualstudio.com/fabrikate/_build/results?buildId=5237&view=results)

**Expected behavior:**

**Screenshots:**

**Additional context:**
Since we're already at Go > 1.11, we need to update the `azure-pipeline.yaml` to use go modules which fabrikate [already supports](https://github.com/microsoft/fabrikate/blob/develop/docs/contributing.md#cloning-fabrikate). 

**Desktop (please complete the following information):**

- OS:

**Additional context**

**Comment by edaena** [comment]
@evanlouie feel free to add additional information.

**Comment by andrebriggs** [comment]
@andrewDoing can we close this?

**Comment by andrewDoing** [comment]
@andrebriggs Yes, there's a new, more specific issue
