### ISSUE TITLE
Support helm version >= 3.3.2

### ISSUE THREAD

**Issue by roger-reed** [microsoft/fabrikate#316]
**As a:**
User of Fabrikate
**I want:**
it to support helm 3.3.2 by not adding the stable repo.  This version of helm introduced a breaking change.  Per release notes https://github.com/helm/helm/releases/tag/v3.3.2:
"One breaking change was made: The default behavior of helm repo add was changed: It no longer overwrites repositories by default. The flag --force-update was added to helm repo add to allow a repo to be overwritten. The flag --no-update still exists, but does nothing. This change accords with the Helm policy for allowing minor breaking changes in the name of security."
**So that:**
we can continue to use the latest releases of helm and that we can use our own localized proxy to the stable repo 
**Describe the solution you'd like:**
My preference is to not add stable in the Fabrikate code.  We use JFrog Artifactory as a proxy to the stable Google repo, and would prefer to use that.  By adding the stable repo in the Fabrikate code it is kind making the decision on what repo to use, and that should left up to the user.  
**Describe alternatives you've considered:**
An alternative would be to add the --force-update, but I would prefer not to go that route because of the other reason noted above.
**Additional context:**
None

**Comment by evanlouie** [comment]
closed in https://github.com/microsoft/fabrikate/commit/bedf1a566a1cc286badfa9ec59c5174304b04ab6

**Comment by evanlouie** [comment]
Closing: we no longer add the stable repo
