### ISSUE TITLE
Validation fails when running `fab generate ...` in Azure DevOps Pipeline build

### ISSUE THREAD

**Issue by yradsmikham** [Microsoft/fabrikate#49]
The new version of Fabrikate appears to include validation of emitted resource manifests after generation. However this is a problem when running Fabrikate in Azure Pipeline Build because the agent that spawns is unaware of AKS, and thus will fail. This obviously does not fail when running Fabrikate locally.

The logs are showing the following error:

`2019-02-07T23:17:22.5370522Z time="07-02-2019 23:17:22" level=error msg="helm template failed with: unable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch-curator.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch-curator.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch-fluentd-kibana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch-fluentd-kibana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch-fluentd-kibana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/fluentd-elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/fluentd-elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/fluentd-elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/fluentd-elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/fluentd-elasticsearch.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/kibana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/kibana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/elasticsearch-fluentd-kibana/kibana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/fabrikate-jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/fabrikate-jaeger/jaeger.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-adapter.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus-grafana.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\nunable to recognize \"generated/prod/infra/prometheus-grafana/prometheus.yaml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\n: output: \n"
2019-02-07T23:17:22.5385509Z Error: exit status 1`

Could we add an argument for running `fab generate...` (e.g. --no-validation) that will skip the kubectl validation?

**Comment by timfpark** [comment]
Addressed in https://github.com/Microsoft/fabrikate/commit/95759e46ee7f60bc085e82beae60bdb7a825139f
