### ISSUE TITLE
Wholesale coercion to strings causing issues when type expected

### ISSUE THREAD

**Issue by timfpark** [Microsoft/fabrikate#56]
Current approach, of using coercion to force all values to strings, is causing errors when the downstream YAML expects a different type, like the Grafana one:

t=2019-02-10T18:08:55+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `1` into int64"

Since the simplest possible thing isn't working, investigate a more complex approach around coercing to the type that will win the merge (eg. the existing type).

**Comment by andrebriggs** [comment]
Seeing the same issue in Grafana logs

```
t=2019-02-12T02:47:01+0000 lvl=info msg="Initializing NotificationService" logger=server
t=2019-02-12T02:47:01+0000 lvl=info msg="Initializing ProvisioningService" logger=server
t=2019-02-12T02:47:01+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `1` into int64"
```

**Comment by timfpark** [comment]
The right fix for this is to fix the underlying library that is complaining about differing types between the two values, even though the two values will never be merged (since we have a "highest in hierarchy wins" system for config).

I am going to fork the underlying library (https://github.com/InVisionApp/conjungo), fix that, PR it, and in the meantime, use my fork for Fabrikate.

**Comment by timfpark** [comment]
Release https://github.com/Microsoft/fabrikate/releases/tag/0.2.2 addresses this issue.
