### ISSUE TITLE
how would I attach an already created nginx-ingress-controller with external ip to kibana

### ISSUE THREAD

**Issue by hectoralicea** [Microsoft/fabrikate#57]
I'm a newbie at this.
How would I attach an already created nginx-ingress-controller with external ip to kibana

`
[root@aks-bastion01 ~]# kubectl get service -l app=nginx-ingress -n acc
NAME                                    TYPE           CLUSTER-IP   EXTERNAL-IP     PORT(S)                      AGE
ingress-nginx-ingress-controller        LoadBalancer   10.2.0.70    4.4.8.123   80:32121/TCP,443:30899/TCP   45m
ingress-nginx-ingress-default-backend   ClusterIP      10.2.0.176   <none>          80/TCP 
`

**Comment by timfpark** [comment]
This is not related to the Fabrikate project itself, closing here.
