### ISSUE TITLE
Getting no matches for kind "APIResourceList" in version "v1" when kubectl apply --recursive -f .

### ISSUE THREAD

**Issue by hectoralicea** [Microsoft/fabrikate#58]
Getting the belows errors when I `kubectl apply --recursive -f .` .  But if I delete these files

rm -rf ./fabrikate/examples/getting-started/generated/prod/.kube ./fabrikate/examples/getting-started/.kube

Everything works second time around.  

How do i get these .kube directories and cache files, not not get generated and to use the one in my starting directory.

`
creating kubernetes namespace elasticsearch
namespace/elasticsearch created
configmap/elasticsearch-curator-config created (dry run)
cronjob.batch/elasticsearch-curator created (dry run)
namespace/elasticsearch configured (dry run)
namespace/fluentd created (dry run)
namespace/kibana created (dry run)
configmap/elasticsearch created (dry run)
serviceaccount/elasticsearch-client created (dry run)
serviceaccount/elasticsearch-data created (dry run)
serviceaccount/elasticsearch-master created (dry run)
service/elasticsearch-client created (dry run)
service/elasticsearch-discovery created (dry run)
deployment.apps/elasticsearch-client created (dry run)
statefulset.apps/elasticsearch-data created (dry run)
statefulset.apps/elasticsearch-master created (dry run)
configmap/fluentd-elasticsearch created (dry run)
serviceaccount/fluentd-elasticsearch created (dry run)
clusterrole.rbac.authorization.k8s.io/fluentd-elasticsearch created (dry run)
clusterrolebinding.rbac.authorization.k8s.io/fluentd-elasticsearch created (dry run)
daemonset.apps/fluentd-elasticsearch created (dry run)
configmap/kibana created (dry run)
service/kibana created (dry run)
deployment.apps/kibana created (dry run)
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/admissionregistration.k8s.io/v1alpha1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/admissionregistration.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/apiextensions.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/apiregistration.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/apps/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/apps/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/apps/v1beta2/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/authentication.k8s.io/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/authentication.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/authorization.k8s.io/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/authorization.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/autoscaling/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/autoscaling/v2beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/batch/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/batch/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/certificates.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/events.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/extensions/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/networking.k8s.io/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/policy/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/rbac.authorization.k8s.io/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/rbac.authorization.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
error validating ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/servergroups.json": error validating data: [ValidationError(APIGroupList.groups[0]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[1]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[2]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[3]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[4]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[5]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[6]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[7]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[8]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[9]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[10]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[11]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[12]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[13]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[14]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[15]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup, ValidationError(APIGroupList.groups[16]): missing required field "serverAddressByClientCIDRs" in io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup]; if you choose to ignore these errors, turn validation off with --validate=false
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/servicecatalog.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/storage.k8s.io/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/storage.k8s.io/v1beta1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
unable to recognize ".kube/cache/discovery/aksalfresc_aksalfrescoresou_484e84_e37dc3df.hcp.eastus2.azmk8s.io_443/v1/serverresources.json": no matches for kind "APIResourceList" in version "v1"
`

**Comment by hectoralicea** [comment]
Appears if I delete these .kube directories 
```
../../../../examples/getting-started/generated/prod/.kube
../../../../examples/getting-started/.kube

```
right before the kubectrl apply, I do not get the above error.  This is the step I added before the kubectl apply

```
find ../../../.. -name '.kube' -type d -prune -exec rm -rf {} \;
kubectl apply --recursive -f .

```

**Comment by timfpark** [comment]
We have migrated the example out of the repo and into another sample repo such that it can be kept up to date.
