### ISSUE TITLE
Install is slow, with repetitive git clones of the same helm repos  

### ISSUE THREAD

**Issue by timfpark** [Microsoft/fabrikate#62]
Fabrikate, as currently written, `git clone`s the helm repo for a particular chart with `--depth 1` (to only fetch the specific commit desired by the user) but it also clones all of the other charts in the other paths that are unneeded.  As an operator or developer, I don't want to have to wait for slow CI/CD builds.

This issue tracks work, yet undesigned, that would make this faster for developers and operators, but yet still enables functionality like differing locked versions in different components.

**Comment by dtzar** [comment]
Would be great to have a way to detect existing cache/versions present on disk
