### ISSUE TITLE
Support fab generation using a private repos for subcomponents

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/fabrikate#72]
Currently, fab generation operates normally when definition files are stored in public repos. However, in the case where definition files are stored in multiple private repos, fab generate will fail. Users should have the flexibility to use a personal access token set in an environment variable as part of the fabrikate definition file. This should provide users the ability to use multiple private repos from various git hosts (ADO, Github, etc.).

Example component.yaml:
```
{
    "name": "cloud-native-infra",
    "subcomponents": [
        {
            "name": "elasticsearch-fluentd-kibana",
            "source": "https://github.com/timfpark/fabrikate-elasticsearch-fluentd-kibana",
            "method": "git"
            "token": "$ACCESS_TOKEN"
        }
    ]
}

```

**Comment by bnookala** [comment]
Closed by the addition of access.yaml: https://github.com/microsoft/fabrikate/blob/master/docs/auth.md
