### ISSUE TITLE
Allow environment names to be part of top-level component.yaml

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/fabrikate#73]
This will help us with multi cluster config, and when we bring in canaries it will be helpful to specify an environment

**Comment by timfpark** [comment]
@samiyaakhtar Could you provide more details about the user story here?

**Comment by samiyaakhtar** [comment]
I believe this was a result of a discussion in GitOps, I can't seem to recall much, @andrebriggs?

**Comment by andrebriggs** [comment]
I don't recall this exactly. Given the title of the issue I can't think of any pressing need related to that. I think the `config/(env name).yaml` model works for us.

@samiyaakhtar We can probably close this
